# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 00:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=500)),
                ('host_address', models.CharField(max_length=150)),
                ('identifier', models.UUIDField(default=uuid.uuid4)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('address1', models.CharField(blank=True, default='', max_length=150)),
                ('address2', models.CharField(blank=True, default='', max_length=150)),
                ('zipcode', models.CharField(blank=True, default='', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('rental_date', models.DateTimeField(blank=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('rental_station', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='rental_client_station', to='core.Client')),
            ],
        ),
        migrations.CreateModel(
            name='RentalObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('station_id', models.IntegerField(blank=True, null=True)),
                ('is_return', models.NullBooleanField()),
                ('rental_cost', models.IntegerField(blank=True, null=True)),
                ('current_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rental_objects', to='core.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=24)),
                ('credits_purchased', models.BigIntegerField(blank=True, null=True)),
                ('price_per_credit', models.DecimalField(decimal_places=2, max_digits=24)),
                ('is_completed', models.BooleanField(default=False)),
                ('transaction_code', models.CharField(max_length=36, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('last_update', models.DateTimeField(auto_now=True)),
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('balance', models.BigIntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rentalobject',
            name='current_tenant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rental',
            name='rented_object',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.RentalObject'),
        ),
        migrations.AddField(
            model_name='rental',
            name='return_station',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_client_station', to='core.Client'),
        ),
        migrations.AddField(
            model_name='rental',
            name='tenant_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
