# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 01:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='rental_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='rental_station',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='rental_client_station', to='server.Client'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='return_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='return_station',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_client_station', to='server.Client'),
        ),
    ]
