# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170709_0137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalobject',
            old_name='current_tenant_user',
            new_name='current_tenant',
        ),
    ]
