# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 03:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170808_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalobject',
            name='current_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rental_objects', to='core.Client'),
        ),
    ]
