# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 03:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170727_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalobject',
            name='current_tenant',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
