# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 02:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
        ('core', '0003_auto_20170815_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=24)),
                ('credits_purchased', models.BigIntegerField(blank=True, null=True)),
                ('price_per_credit', models.DecimalField(decimal_places=2, max_digits=24)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('last_update', models.DateTimeField(auto_now=True)),
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('balance', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
