# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 02:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170817_2330'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransactionHistory',
            new_name='Transaction',
        ),
    ]
