# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170817_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
