# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_profile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_code',
            field=models.CharField(max_length=36, null=True, unique=True),
        ),
    ]
