# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_transaction_transaction_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
