# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 03:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20170924_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='is_confirmed',
        ),
        migrations.AlterField(
            model_name='rental',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='return_station',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_client_station', to='core.Client'),
        ),
    ]
