# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20170927_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalobject',
            name='station_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
