# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rentalobject_station_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalobject',
            name='is_return',
            field=models.NullBooleanField(),
        ),
    ]
