# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientreservation',
            name='rental_object',
        ),
        migrations.RemoveField(
            model_name='clientreservation',
            name='tenant_user',
        ),
        migrations.DeleteModel(
            name='ClientReservation',
        ),
    ]
